# This configuration file loads up before any MMV related stuff is set
# and it doesn't change anything on the final video, this file is mostly
# for configurations such as logging, namely Python stuff or QOL, let
# you name it.

logging:
  log_to_file: true
  log_level: "info"  # critical, debug, error, info
  log_format: "pretty"  # informational, pretty, economic, onlymessage

window:
  intensity_responsiveness: 0.2
  rotation_responsiveness: 0.2
  zoom_responsiveness: 0.2
  drag_responsiveness: 0.3
  time_responsiveness: 0.09
  drag_momentum: 0.6
  action_message_timeout: 1.3

  3d:
    mouse_sensitivity: 1
    rotate_responsiveness: 0.8
    zoom_responsiveness: 0.2
    walk_responsiveness: 0.3

fluidsynth:
  audio_backend_linux: pulseaudio
  # soundfont: "/usr/share/soundfonts/freepats-general-midi.sf2"
  soundfont: "/usr/share/soundfonts/FluidR3_GM.sf2"

audio:
  sample_rate: 48000
  batch_size: 4096

ffmpeg:
  preset: slow
  crf: 18
  tune: film
  vflip: True
