# This configuration file loads up before any MMV related stuff is set
# and it doesn't change anything on the final video, this file is mostly
# for configurations such as logging, namely Python stuff or QOL, let
# you name it.


[logging]
log_to_file = true
log_level = "debug"  # critical, debug, error, info, warn, notset
log_format = "pretty"  # informational, pretty, economic, onlymessage

# MMVSkia package configuration
[mmvskia]

    # Stop code at some specific point?
    [mmvskia.flow]
    stop_at_interface_init = false
    stop_at_mmv_core_run = true

    # # Logging

    # Please be careful some functions gets called a lot or 
    # simply have too much data to output, mainly mmvcore.run
    # log_modulators, these should be avoided as the log file will
    # grow insanely large for small videos, very quickly

    [mmvskia.mmvcore]
        log_creation = true
        [mmvskia.mmvcore.run]
            log_step = false
            log_offsetted_step = false
            log_modulators = false
            log_next_steps = false

    [mmvskia.mmvgenerator]
        log_creation = true
        log_get_unique_id = true
        [mmvskia.mmvgenerator.particle_generator]
            log_action = true
        
    [mmvskia.mmvanimation]
        log_creation = true
        [mmvskia.mmvanimation.mklayers_until]
            log_action = false
            log_new_layers = false

    [mmvskia.mmvimage]
        log_creation = true
        log_get_unique_id = true
        [mmvskia.mmvimage._reset_effects_variables]
            log_action = false
        [mmvskia.mmvimage.create_canvas]
            log_action = true
            log_steps = true
        [mmvskia.mmvimage.reset_canvas]
            log_action = false
        [mmvskia.mmvimage.next]
            log_current_step = false
            log_became_deletable = false

    [mmvskia.mmvimage_configure]
        [mmvskia.mmvimage_configure.load_image]
            log_action = false
            log_get_abspath = false
            log_load_image = false
        [mmvskia.mmvimage_configure.init_animation_layer]
            log_action = true
        [mmvskia.mmvimage_configure.start_or_reset_this_animation]
            log_action = true
        [mmvskia.mmvimage_configure.set_animation_index]
            log_action = true
        [mmvskia.mmvimage_configure.set_this_animation_steps]
            log_action = true
        [mmvskia.mmvimage_configure.resize_image_to_resolution]
            log_action = true
        [mmvskia.mmvimage_configure.resize_image_to_video_resolution]
            log_action = true
        [mmvskia.mmvimage_configure.add_module_video]
            log_action = true
        [mmvskia.mmvimage_configure.add_path_point]
            log_action = true
        [mmvskia.mmvimage_configure.simple_add_path_modifier_shake]
            log_action = true

        # MMVSkiaVectorial calls
        [mmvskia.mmvimage_configure.add_vectorial_by_kwargs]
            log_action = true
        [mmvskia.mmvimage_configure.add_module_visualizer]
            log_action = true
        [mmvskia.mmvimage_configure.add_module_progression_bar]
            log_action = true
        [mmvskia.mmvimage_configure.add_module_piano_roll]
            log_action = true

        # Modifiers
        [mmvskia.mmvimage_configure.add_module_resize]
            log_action = true
        [mmvskia.mmvimage_configure.add_module_blur]
            log_action = true
        [mmvskia.mmvimage_configure.add_module_swing_rotation]
            log_action = true
        [mmvskia.mmvimage_configure.add_module_linear_rotation]
            log_action = true
        [mmvskia.mmvimage_configure.add_module_vignetting]
            log_action = true
        

[mmvshader]
    [mmvshader.flow]
    stop_at_run_command = false